services:
  database:
    container_name: docker_db
    image: "postgres:17-alpine"
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - database-data:/var/lib/postgresql/data

  flyway:
    container_name: docker_flyway
    image: "flyway/flyway"
    command: [ "migrate", "-X", "-configFiles=/flyway/flyway.conf" ]
    volumes:
      - database-data:/var/lib/docker_flyway/data/
      - ./flyway/conf/flyway.conf:/flyway/flyway.conf
      - .:/flyway/sql
    depends_on:
      - database

volumes:
  database-data:

networks:
  postgres-network:
    driver: bridge
